[[AutoscaleRule]]
  Metric = "ram"
  AllowMigration = false
  AllowRestart = false
  [AutoscaleRule.Limits]
    Min = 128
    Max = 8192
    Step = 256
  [AutoscaleRule.Thresholds]
    [AutoscaleRule.Thresholds.Up]
      Threshold = 80
      Period = 300
    [AutoscaleRule.Thresholds.Down]
      Threshold = 20
      Period = 1200

[[AutoscaleRule]]
  Metric = "cpu"
  AllowMigration = false
  AllowRestart = false
  [AutoscaleRule.Limits]
    Min = 1000
    Max = 2000
    Step = 100
  [AutoscaleRule.Thresholds]
    [AutoscaleRule.Thresholds.Up]
      Threshold = 80
      Period = 300
    [AutoscaleRule.Thresholds.Down]
      Threshold = 20
      Period = 1200
