[[Rule]]
  Name = "http"
  Protocol = "TCP"
  LocalPort = 80
  RemotePort = 0
  RemoteNet = ["0.0.0.0/0"]

[[Rule]]
  Name = "https"
  Protocol = "TCP"
  LocalPort = 443
  RemotePort = 0
  RemoteNet = ["0.0.0.0/0"]

[[Rule]]
  Name = "ssh"
  Protocol = "TCP"
  LocalPort = 22
  RemotePort = 0
  RemoteNet = ["192.0.2.0/24", "198.51.100.0/24"]
